sudo: false
language: php
dist: trusty

matrix:
  fast_finish: true
  include:
  - php: 7.1
  - php: 7.2

before_install:
- composer require "squizlabs/php_codesniffer=*"
# Speed up build time by disabling Xdebug when its not needed.
- phpenv config-rm xdebug.ini || echo 'No xdebug config.'


before_script:
- composer install
- if [[ $CUSTOM_INI == "1" && ${TRAVIS_PHP_VERSION:0:1} == "5" ]]; then phpenv config-add php5-testingConfig.ini; fi
- if [[ $CUSTOM_INI == "1" ]] && [[ ${TRAVIS_PHP_VERSION:0:1} == "7" || $TRAVIS_PHP_VERSION == "nightly" ]]; then phpenv config-add php7-testingConfig.ini; fi

script:
- php vendor/bin/phpcs --config-set php_path php
#- phpunit tests/AllTests.php
- phpcs --standard=$(if [ -e phpcs.xml ]; then echo phpcs.xml; else echo FuckMe; fi) $(find . -name '*.php')

cache:
  directories:
  - "vendor"
