sudo: false
language: php
php:
  - 7.2
dist: trusty

node_js:
- "stable"

matrix:
  fast_finish: true
  include:
  - php: 7.2

before_install:
- npm i
- composer require "squizlabs/php_codesniffer=*"
# Speed up build time by disabling Xdebug when its not needed.
- phpenv config-rm xdebug.ini || echo 'No xdebug config.'


before_script:
- if [[ $CUSTOM_INI == "1" ]] && [[ ${TRAVIS_PHP_VERSION:0:1} == "7.2" ]]; then phpenv config-add php7.2-testingConfig.ini; fi

script:
- npm build
#- phpunit tests/AllTests.php
- php $TRAVIS_BUILD_DIR/vendor/bin/phpcs $(find $TRAVIS_BUILD_DIR/system -name '*.php') -p -s -v -n . --standard=$TRAVIS_BUILD_DIR/.phpcs.xml --extensions=php

cache:
  directories:
  - "vendor"
  - "node_modules"

after_success:
- sh $TRAVIS_BUILD_DIR/shell/PR-comment.sh
