sudo: false
language: php
dist: trusty

matrix:
  fast_finish: true
  include:
  - php: 7.2

before_install:
- npm i
- composer require "squizlabs/php_codesniffer=*"
# Speed up build time by disabling Xdebug when its not needed.
- phpenv config-rm xdebug.ini || echo 'No xdebug config.'


before_script:
- if [[ $CUSTOM_INI == "1" ]] && [[ ${TRAVIS_PHP_VERSION:0:1} == "7" ]]; then phpenv config-add php7-testingConfig.ini; fi

script:
- npm build
- php vendor/bin/phpcs --config-set php_path php
#- phpunit tests/AllTests.php
- php vendor/bin/phpcs --standard=$(if [ -e phpcs.xml ]; then echo phpcs.xml; else echo Error; fi) $(find ./system -path ./vendor -prune -o -name '*.php')

cache:
  directories:
  - "vendor"
  - "node_modules"

after_success:
- sh ./shell/PR-comment.sh
