sudo: false
language: php
dist: trusty

node_js:
- "stable"

matrix:
  fast_finish: true
  include:
  - php: 7.2

before_install:
- npm i
- composer require "squizlabs/php_codesniffer=*"
# Speed up build time by disabling Xdebug when its not needed.
- phpenv config-rm xdebug.ini || echo 'No xdebug config.'


before_script:
- if [[ "$SNIFF" == "1" ]]; then
  phpcs --config-set installed_paths $TRAVIS_BUILD_DIR/.phpcs.xml;
  fi
- if [[ $CUSTOM_INI == "1" ]] && [[ ${TRAVIS_PHP_VERSION:0:1} == "7" ]]; then phpenv config-add php7-testingConfig.ini; fi

script:
- npm build
- php $TRAVIS_BUILD_DIR/vendor/bin/phpcs --config-set php_path php
#- phpunit tests/AllTests.php
- php $TRAVIS_BUILD_DIR/vendor/bin/phpcs -v $(find $TRAVIS_BUILD_DIR/system -name '*.php')

cache:
  directories:
  - "vendor"
  - "node_modules"

after_success:
- sh $TRAVIS_BUILD_DIR/shell/PR-comment.sh
